FROM jenkins/inbound-agent:latest

USER root

# Instalacja Node.js, npm, Git, Docker CLI, curl, jq
RUN apt-get update && apt-get install -y \
    curl \
    git \
    jq \
    docker.io \
    && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs \
    && npm install -g npm \
    && apt-get clean

# Sprawdzenie wersji
RUN node -v && npm -v && git --version && docker --version && jq --version